# Generated by Django 5.0.2 on 2024-03-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consumer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='vendor',
            managers=[
            ],
        ),
    ]
