# Generated by Django 5.0.2 on 2024-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_consumer_options_alter_vendor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
