# Generated by Django 5.0.2 on 2024-03-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
