# Generated by Django 5.0.2 on 2024-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_vendor_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='full_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
