# Generated by Django 5.0.2 on 2024-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_consumer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='product_sold',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
