# Generated by Django 5.0.2 on 2024-04-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_vendor_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='product_sold',
        ),
    ]
