# Generated by Django 5.0.2 on 2024-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_remove_chat_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read2',
            field=models.BooleanField(default=False),
        ),
    ]
