# Generated by Django 5.0.2 on 2024-04-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_is_read2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read3',
            field=models.BooleanField(default=False),
        ),
    ]
