# Generated by Django 5.0.2 on 2024-04-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_is_read3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='is_read2',
            new_name='receiver_seen',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='is_read3',
            new_name='sender_seen',
        ),
    ]
