# Generated by Django 5.0.2 on 2024-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='img_url',
            field=models.ImageField(blank=True, default='No image.svg', null=True, upload_to='static/images'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
