# Generated by Django 5.0.2 on 2024-03-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productinventory_img_url_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='productAttributes',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='sku',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributevalues', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributevaluess', to='inventory.productattributevalue')),
                ('productinventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productattributevaluess', to='inventory.productinventory')),
            ],
            options={
                'unique_together': {('attributevalues', 'productinventory')},
            },
        ),
        migrations.AddField(
            model_name='productinventory',
            name='productAttributes',
            field=models.ManyToManyField(related_name='product_attribute_values', through='inventory.ProductAttributeValues', to='inventory.productattributevalue'),
        ),
    ]
