# Generated by Django 5.0.2 on 2024-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productinventory_productattributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='store_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
