# Generated by Django 5.0.2 on 2024-04-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_shippingaddress_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='stock_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='inventory.product'),
        ),
    ]
