# Generated by Django 5.0.2 on 2024-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productinventory_stock_sold_alter_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='product_sold',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
