# Generated by Django 5.0.2 on 2024-04-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_productinventory_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='product_sold',
        ),
    ]
