# Generated by Django 5.0.2 on 2024-04-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_salesrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='stock_sold',
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory'),
        ),
    ]
